# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'security' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for security
  pod 'SAMKeychain'



  target 'securityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'securityUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
