# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'defineCamera' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for defineCamera
  pod 'Masonry', '1.0.2'
  pod 'DBCamera', '~>2.4'
  pod 'FMDB', '~> 2.6.2'
  pod 'IQKeyboardManager', '~> 4.0.8'

  target 'defineCameraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'defineCameraUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
